add failing step in workflow1

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -14,6 +14,8 @@ jobs:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
+      - name: To show error
+        run: echo "Should fail at this point ..." ; exit 1
       - name: Run a one-line script
-        run: echo "CI in GitHub actions"
+        run: echo "CI in GitHub"
         
